### ISSUE TITLE
大佬感谢您提供的模板想请教下

### ISSUE THREAD

**Issue by MaxRubby** [yaoyz96/els-cas-templates#3]
想请教下是不是爱思唯尔期刊的初稿都可以用这个提交呢，我在官网上找的和已出版的差别很大，感觉不像模板像用法举例
![Clip_20240529_155524](https://github.com/yaoyz96/els-cas-templates/assets/57722647/3f2859af-9322-42a7-8366-d91844b0b923)

**Comment by yaoyz96** [comment]
不用和已出版的格式一样，按照期刊要求使用这些模板就可以了，每不同期刊有可能规定单栏/双栏。

**Comment by yaoyz96** [comment]
> 想请教下是不是爱思唯尔期刊的初稿都可以用这个提交呢，我在官网上找的和已出版的差别很大，感觉不像模板像用法举例 ![Clip_20240529_155524](https://private-user-images.githubusercontent.com/57722647/334708986-3f2859af-9322-42a7-8366-d91844b0b923.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Njk4MjksIm5iZiI6MTcxNjk2OTUyOSwicGF0aCI6Ii81NzcyMjY0Ny8zMzQ3MDg5ODYtM2YyODU5YWYtOTMyMi00MmE3LTgzNjYtZDkxODQ0YjBiOTIzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA3NTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMzIxYTMxN2IwNjA5ODViMGM1MjRmM2NkZTU3NDk1N2Q0ZjAwMjRhOGQxN2ZlMzFkOTgyODVkOTU5MGY2MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RVszijeCyuSW8Z9JiYj5AeCzbDHg4uUNCtdvssO3Rdc)

不用和已出版的格式一样，按照期刊要求使用这些模板就可以了，每不同期刊有可能规定单栏/双栏。

**Comment by MaxRubby** [comment]
如果期刊没有明确规定，只是跳转到爱思唯尔推荐模版，可以用您发布的这个吗
![image](https://github.com/yaoyz96/els-cas-templates/assets/57722647/e9d6e7cc-87e7-4a34-82b5-22d8b365b6b4)

**Comment by yaoyz96** [comment]
> 如果期刊没有明确规定，只是跳转到爱思唯尔推荐模版，可以用您发布的这个吗 ![image](https://private-user-images.githubusercontent.com/57722647/334712290-e9d6e7cc-87e7-4a34-82b5-22d8b365b6b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzAyNzcsIm5iZiI6MTcxNjk2OTk3NywicGF0aCI6Ii81NzcyMjY0Ny8zMzQ3MTIyOTAtZTlkNmU3Y2MtODdlNy00YTM0LTgyYjUtMjJkOGIzNjViNmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA4MDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MjJiYjkxZDVjZDJlZDYxM2Q5NDA5YjgxMjA5NWZmYmE0MGFlZWMxZGZhMTY3NDYyODAxNWU1Y2I1ZjcyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QjHszPzmO2nEqD5awPPrik50DJeZ19wwEGSLf2nqzuI)

这里说了推荐使用 elsarticel.cls，用 https://github.com/yaoyz96/elsarticle

**Comment by MaxRubby** [comment]
好的 感谢大佬👍👍👍
